services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: snads-backend
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - kafka
  mongo:
    image: mongo:latest
    restart: always
    container_name: snads-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: lordisrael
      MONGO_INITDB_ROOT_PASSWORD: loveiman
  redis:
    image: redis:7
    container_name: snads-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: snads-zookeeper
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:${ZOOKEEPER_CLIENT_PORT}"
    environment:
      ZOOKEEPER_CLIENT_PORT: ${ZOOKEEPER_CLIENT_PORT}
      ZOOKEEPER_TICK_TIME: ${ZOOKEEPER_TICK_TIME}
  # kafka:
  #   image: wurstmeister/kafka:latest
  #   container_name: snads-kafka
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
  #     KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #   volumes:
  #     - kafka_data:/kafka/data
  #   depends_on:
  #     - zookeeper
  kafka:
    image: wurstmeister/kafka:latest
    container_name: snads-kafka
    ports:
      - "9092:9092"   # internal
      - "9093:9093"   # external
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - kafka_data:/kafka/data
    depends_on:
      - zookeeper
volumes:
  mongo_data:
  redis_data:
  kafka_data: 