
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - REDIS_URL=${REDIS_URL}
      - MONGO_URI=${MONGO_URI_DEV}
      - KAFKA_BROKER=${KAFKA_BROKER}
    volumes:
      - .:/usr/src/app
    command: npm run dev
